_wandb:
    value:
        cli_version: 0.25.0
        e:
            nkecfja34cy6iylaut1ata71au8zw9rt:
                args:
                    - -d
                    - mnist
                    - -e
                    - "5"
                    - -b
                    - "32"
                    - -o
                    - momentum
                    - -lr
                    - "0.001"
                    - -nhl
                    - "3"
                    - -sz
                    - "128"
                    - "128"
                    - "128"
                    - -a
                    - relu
                    - -w_i
                    - xavier
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "509722226688"
                        used: "397727379456"
                email: tanmoyghosh704@gmail.com
                executable: C:\python3_10_11\DA6401_Assignment_1\.venv\scripts\python.exe
                git:
                    commit: fadf36d5b8dce4ca4cbf79a500f8cb591c305ce6
                    remote: https://github.com/tanmoyghosh704-lang/DA6401_Assignment_1.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-a16d2db4-5e71-e067-816b-1f1149755cc7
                host: TANMOY
                memory:
                    total: "14877257728"
                os: Windows-10-10.0.26200-SP0
                program: -m src.train
                python: CPython 3.10.11
                root: C:\python3_10_11\DA6401_Assignment_1
                startedAt: "2026-02-21T20:21:18.046746Z"
                writerId: nkecfja34cy6iylaut1ata71au8zw9rt
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.11
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 32
dataset:
    value: mnist
epochs:
    value: 5
hidden_size:
    value:
        - 128
        - 128
        - 128
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
num_layers:
    value: 3
optimizer:
    value: momentum
weight_decay:
    value: 0
weight_init:
    value: xavier
