wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
dataset:
  value: mnist
epochs:
  value: 10
learning_rate:
  value: 0.0001
loss:
  value: mean_squared_error
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: random
