wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
learning_rate:
  value: 0.001
loss:
  value: mean_squared_error
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: random
