wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
learning_rate:
  value: 0.001
loss:
  value: cross_entropy
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: xavier
