wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
dataset:
  value: mnist
epochs:
  value: 10
learning_rate:
  value: 0.01
loss:
  value: mean_squared_error
optimizer:
  value: nadam
weight_decay:
  value: 0
weight_init:
  value: random
