wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
dataset:
  value: mnist
epochs:
  value: 10
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
