_wandb:
    value:
        cli_version: 0.25.0
        e:
            mwdducxvpi51htpg98v3bnkv00qdsd61:
                args:
                    - -d
                    - mnist
                    - -e
                    - "10"
                    - -o
                    - adam
                    - -a
                    - relu
                    - -nhl
                    - "6"
                    - -sz
                    - "128"
                    - "128"
                    - "128"
                    - "128"
                    - "128"
                    - "128"
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "509722226688"
                        used: "395206217728"
                email: tanmoyghosh704@gmail.com
                executable: C:\python3_10_11\DA6401_Assignment_1\.venv\Scripts\python.exe
                git:
                    commit: fadf36d5b8dce4ca4cbf79a500f8cb591c305ce6
                    remote: https://github.com/tanmoyghosh704-lang/DA6401_Assignment_1.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-a16d2db4-5e71-e067-816b-1f1149755cc7
                host: TANMOY
                memory:
                    total: "14877257728"
                os: Windows-10-10.0.26200-SP0
                program: -m src.train
                python: CPython 3.10.11
                root: C:\python3_10_11\DA6401_Assignment_1
                startedAt: "2026-02-26T17:56:54.900650Z"
                writerId: mwdducxvpi51htpg98v3bnkv00qdsd61
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.11
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 16
dataset:
    value: mnist
epochs:
    value: 10
hidden_size:
    value:
        - 128
        - 128
        - 128
        - 128
        - 128
        - 128
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
num_layers:
    value: 6
optimizer:
    value: adam
weight_decay:
    value: 0
weight_init:
    value: xavier
