wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 10
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
optimizer:
  value: rmsprop
weight_decay:
  value: 0
weight_init:
  value: xavier
