wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
dataset:
  value: mnist
epochs:
  value: 10
learning_rate:
  value: 0.01
loss:
  value: cross_entropy
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
