_wandb:
    value:
        cli_version: 0.25.0
        e:
            tpfs6htv7evl4hlnghgtnmkfsa69i076:
                args:
                    - -d
                    - mnist
                    - -e
                    - "10"
                    - -o
                    - nadam
                    - -a
                    - relu
                    - -l
                    - mean_squared_error
                    - -lr
                    - "0.001"
                    - -nhl
                    - "3"
                    - -sz
                    - "128"
                    - "128"
                    - "128"
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "509722226688"
                        used: "395186872320"
                email: tanmoyghosh704@gmail.com
                executable: C:\Users\tanmo\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: 50ac41fcceaf55069876862dae5ffefc4127bc45
                    remote: https://github.com/tanmoyghosh704-lang/DA6401_Assignment_1.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-a16d2db4-5e71-e067-816b-1f1149755cc7
                host: TANMOY
                memory:
                    total: "14877257728"
                os: Windows-10-10.0.26200-SP0
                program: -m src.train
                python: CPython 3.10.11
                root: C:\python3_10_11\DA6401_Assignment_1
                startedAt: "2026-02-26T19:13:15.847837Z"
                writerId: tpfs6htv7evl4hlnghgtnmkfsa69i076
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.11
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 16
dataset:
    value: mnist
epochs:
    value: 10
hidden_size:
    value:
        - 128
        - 128
        - 128
learning_rate:
    value: 0.001
loss:
    value: mean_squared_error
num_layers:
    value: 3
optimizer:
    value: nadam
weight_decay:
    value: 0
weight_init:
    value: xavier
