_wandb:
    value:
        cli_version: 0.25.0
        e:
            fhxc9jj5uz3zuece1c6vd6z4u4npizky:
                codePath: c:\python3_10_11\DA6401_Assignment_1\notebooks\wandb_demo.ipynb
                codePathLocal: wandb_demo.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.5"
                disk:
                    /:
                        total: "509722226688"
                        used: "397339795456"
                email: tanmoyghosh704@gmail.com
                executable: c:\python3_10_11\DA6401_Assignment_1\.venv\Scripts\python.exe
                git:
                    commit: 1773abe316114cfb33b96e63562285904eb3b70c
                    remote: https://github.com/tanmoyghosh704-lang/DA6401_Assignment_1.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-a16d2db4-5e71-e067-816b-1f1149755cc7
                host: TANMOY
                memory:
                    total: "14877257728"
                os: Windows-10-10.0.26200-SP0
                program: c:\python3_10_11\DA6401_Assignment_1\notebooks\wandb_demo.ipynb
                python: CPython 3.10.11
                root: c:\python3_10_11\DA6401_Assignment_1\notebooks
                startedAt: "2026-02-21T19:24:15.540840Z"
                writerId: fhxc9jj5uz3zuece1c6vd6z4u4npizky
        m: []
        python_version: 3.10.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
            "4": 3.10.11
            "5": 0.25.0
            "8":
                - 1
                - 3
            "12": 0.25.0
            "13": windows-amd64
